is_training: 1
model_id: 'test'
model: 'Autoformer'
data: 'ILI'
root_path: './data/ETT/'
data_path: './illness/national_illness.csv'
features: 'M'
target: 'OT'
freq: 'h'
checkpoints: './checkpoints/'
seq_len: 36
label_len: 18
pred_len: 24
bucket_size: 4
n_hashes: 4
enc_in: 7
dec_in: 7
c_out: 7
d_model: 512
n_heads: 8
e_layers: 2
d_layers: 1
d_ff: 2048
moving_avg: 25
factor: 3
distil: true
dropout: 0.05
embed: 'timeF'
activation: 'gelu'
output_attention: false
do_predict: false
num_workers: 10
itr: 2
train_epochs: 10
batch_size: 32
patience: 3
learning_rate: 0.0001
des: 'test'
loss: 'mse'
lradj: 'type1'
use_amp: false
use_gpu: false
gpu: 0
use_multi_gpu: false
devices: '0,1,2,3'
